apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ecrpullsecrets.alchemy.com
spec:
  group: alchemy.com
  names:
    kind: ECRPullSecret
    plural: ecrpullsecrets
    singular: ecrpullsecret
    shortNames:
      - ecrps
  scope: Cluster
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        description: "ECR Pull Secret configuration"
        properties:
          spec:
            type: object
            description: "ECR Pull Secret configuration"
            required:
              - secretName
            properties:
              secretName:
                type: string
                description: "Name of the secret that contains the ECR token"
                default: "aws-registry-209202477790"
              namespaces:
                type: array
                description: "List of namespaces to create the secret in"
                items:
                  type: string
    additionalPrinterColumns:
    - name: SecretName
      type: string
      description: "Name of the secret"
      jsonPath: .spec.secretName
    - name: Namespaces
      type: string
      description: "Target namespaces"
      jsonPath: .spec.namespaces
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp